# Generated by Django 4.1.7 on 2023-03-14 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bookmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.bookmodel'),
        ),
    ]
